# Generated by Django 4.2.6 on 2023-10-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catergory',
            new_name='category',
        ),
    ]
