# Generated by Django 4.2.6 on 2023-11-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_catergory_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
