# Generated by Django 4.2.6 on 2023-11-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
