# Generated by Django 4.2.6 on 2023-11-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_picture', models.ImageField(upload_to='pictures')),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.wilaya')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
